apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-inventory
  labels:
    app: product-inventory
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-inventory
  template:
    metadata:
      labels:
        app: product-inventory
    spec:
      containers:
        - name: product-inventory
          image: thisisaarush/product-inventory:latest
          ports:
            - containerPort: 5001
