apiVersion: v1
kind: Service
metadata:
  name: product-inventory
  labels:
    app: product-inventory
spec:
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: product-inventory
  type: ClusterIP
